framework:
    messenger:
        failure_transport: failed

        transports:
            parse_news:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/parse_news'
                serializer: messenger.transport.symfony_serializer
            parse_news_page:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/parse_news_page'
                serializer: messenger.transport.symfony_serializer
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/failed'
                serializer: messenger.transport.symfony_serializer

        routing:
            App\Message\ParseNewsMessage: parse_news
            App\Message\ParseNewsPageMessage: parse_news_page